Add back system squisher for nougat kudo to chet
# Conflicts:
#	config/common.mk
#	tools/colors
#	tools/crusher
#	tools/squisher

diff --git a/tools/crusher b/tools/crusher
--- a/tools/crusher
+++ b/tools/crusher
@@ -28,14 +28,14 @@ then
     APKCERTS=$OUT/obj/PACKAGING/target_files_intermediates/$TARGET_PRODUCT-target_files-$TARGET_BUILD_VARIANT.$USER/META/apkcerts.txt
     if [ ! -f "$APKCERTS" ];
     then
-        echo $red"Set APKCERTS to the path to your apkcerts.txt file"$txtrst
+        echo $CL_RED"Set APKCERTS to the path to your apkcerts.txt file"$CL_RST
         exit 1;
     fi
 fi
 
 if [ ! -f "$APKCERTS" ];
 then
-    echo $red"Invalid path to apkcerts.txt, set APKCERTS to the correct path."$txtrst
+    echo $CL_RED"Invalid path to apkcerts.txt, set APKCERTS to the correct path."$CL_RST
 fi
 
 if [ "$(which pngquant)" != "" ];
@@ -61,27 +61,27 @@ else
             optipng -o7 $1 1> /dev/null 2> /dev/null;
         }
     else
-        echo $red"Please install pngquant or optipng (or both, for improved crushing)"$txtrst
+        echo $CL_RED"Please install pngquant or optipng (or both, for improved crushing)"$CL_RST
         exit 1;
     fi
 fi
 
 if [ "`which aapt`" = "" ];
 then
-    echo $red"Please ensure aapt is in your \$PATH"$txtrst
+    echo $CL_RED"Please ensure aapt is in your \$PATH"$CL_RST
     exit 1;
 fi
 
 if [ "`which zipalign`" = "" ];
 then
-    echo $red"Please ensure zipalign is in your \$PATH"$txtrst
+    echo $CL_RED"Please ensure zipalign is in your \$PATH"$CL_RST
     exit 1;
 fi
 
 if [ -e "$1" ];
 then
     NAME=`basename $1`;
-    echo $cya$OPTSTRING $ylw"$NAME..."$txtrst;
+    echo $CL_CYN$OPTSTRING $CL_YLW"$NAME..."$CL_RST;
 
     if [ "$2" != "" ];
     then
@@ -89,7 +89,7 @@ then
         KEY=build/target/product/security/$2.pk8
         if [ ! -f "$ANDROID_BUILD_TOP/$CERT" ];
         then
-            echo $red"$CERT does not exist!";$txtrst
+            echo $CL_RED"$CERT does not exist!";$CL_RST
             exit 1;
         fi
     else
@@ -97,24 +97,24 @@ then
         [ $QUIET ] || echo "APKINFO: $APKINFO";
         if [ "$APKINFO" = "" ];
         then
-            echo $red"No apk info for $NAME";$txtrst
+            echo $CL_RED"No apk info for $NAME";$CL_RST
             exit 1;
         fi
         CERT=`echo $APKINFO | awk {'print $2'} | cut -f 2 -d "=" | tr -d "\""`;
         KEY=`echo $APKINFO | awk {'print $3'} | cut -f 2 -d "=" | tr -d "\""`;
         if [ "$CERT" = "" ];
         then
-            echo -e $red"Unable to find certificate for $NAME"$txtrst
+            echo -e $CL_RED"Unable to find certificate for $NAME"$CL_RST
             exit 1;
         fi
         if [ "$CERT" = "PRESIGNED" ];
         then
-            echo $grn"$NAME is presigned, skipping"$txtrst
+            echo $CL_GRN"$NAME is presigned, skipping"$CL_RST
             exit 1;
         fi
     fi
 
-    [ $QUIET ] || echo $yellow"Certificate:"$txtrst" $CERT";
+    [ $QUIET ] || echo $CL_YLW"Certificate:"$CL_RST" $CERT";
 
     [ -d $TMPDIR/$NAME ] && rm -rf $TMPDIR/$NAME
     mkdir -p $TMPDIR/$NAME
@@ -123,19 +123,19 @@ then
     unzip -q $BASE/$1
     for x in `find . -name "*.png" | grep -v "\.9.png$" | tr "\n" " "`
     do
-        [ $QUIET ] || echo $grn"Crushing $x"$txtrst
+        [ $QUIET ] || echo $CL_GRN"Crushing $x"$CL_RST
         optimize_png $x
     done
     cp $BASE/$1 $BASE/$1.old
 
-    [ $QUIET ] || echo $grn"Repacking apk.."$txtrst
+    [ $QUIET ] || echo $CL_GRN"Repacking apk.."$CL_RST
     aapt p -0 .dat -0 .dict -0 .arsc -F $NAME .
 
-    [ $QUIET ] || echo $ylw"Resigning with cert: `echo $CERT`"$txtrst
+    [ $QUIET ] || echo $CL_YLW"Resigning with cert: `echo $CERT`"$CL_RST
 
     [ $QUIET ] || echo java -Djava.library.path=$SIGNAPK_JNI_LIBRARY_PATH -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME
     java -Djava.library.path=$SIGNAPK_JNI_LIBRARY_PATH -jar $ANDROID_HOST_OUT/framework/signapk.jar $ANDROID_BUILD_TOP/$CERT $ANDROID_BUILD_TOP/$KEY $NAME signed_$NAME 
-    [ $QUIET ] || echo $grn"Zipalign.."$txtrst
+    [ $QUIET ] || echo $CL_GRN"Zipalign.."$CL_RST
     zipalign -f 4 signed_$NAME $BASE/$1
     if [ ! $QUIET ]; then
         ls -l $BASE/$1.old
